// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArv2avm79I_PEQIywiU-tl_M6Bzp-FhHY',
    appId: '1:886121278075:web:d01e11dc0ef59a4c0a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    authDomain: 'app-thu-tien.firebaseapp.com',
    storageBucket: 'app-thu-tien.appspot.com',
    measurementId: 'G-XSDEM66HZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_2q3Oe7qdPrz8HrV09U0BCB70pCf0_hQ',
    appId: '1:886121278075:android:d3f07c01fee3c7ae0a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    storageBucket: 'app-thu-tien.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPK4Hx1pcHlv3FADyySAbuvmXmah2XB-4',
    appId: '1:886121278075:ios:b41fa7ec9583ee050a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    storageBucket: 'app-thu-tien.appspot.com',
    iosBundleId: 'com.example.appThuTien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPK4Hx1pcHlv3FADyySAbuvmXmah2XB-4',
    appId: '1:886121278075:ios:cdd8b2a947761ba30a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    storageBucket: 'app-thu-tien.appspot.com',
    iosBundleId: 'vn.plminhphu.thutien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArv2avm79I_PEQIywiU-tl_M6Bzp-FhHY',
    appId: '1:886121278075:web:24b6911126843e790a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    authDomain: 'app-thu-tien.firebaseapp.com',
    storageBucket: 'app-thu-tien.appspot.com',
    measurementId: 'G-YCRDPH51GN',
  );
}
