// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQS8PJtOlzpl1nbeBMLLDIInLZ5rk-Y5c',
    appId: '1:1030920963113:web:5d11a8918f21b9e1630838',
    messagingSenderId: '1030920963113',
    projectId: 'app-thu-tien-2',
    authDomain: 'app-thu-tien-2.firebaseapp.com',
    storageBucket: 'app-thu-tien-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzq8J-sS6TtOM20cJOxdLN7odOeMaZpnI',
    appId: '1:1030920963113:android:4077d3f040b43283630838',
    messagingSenderId: '1030920963113',
    projectId: 'app-thu-tien-2',
    storageBucket: 'app-thu-tien-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBQ1SZ94eX2QQhX3b9GMr3ZYNqlgTOwXw',
    appId: '1:1030920963113:ios:9779b0174610d43b630838',
    messagingSenderId: '1030920963113',
    projectId: 'app-thu-tien-2',
    storageBucket: 'app-thu-tien-2.firebasestorage.app',
    iosBundleId: 'vn.plminhphu.thutien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPK4Hx1pcHlv3FADyySAbuvmXmah2XB-4',
    appId: '1:886121278075:ios:cdd8b2a947761ba30a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    storageBucket: 'app-thu-tien.appspot.com',
    iosBundleId: 'vn.plminhphu.thutien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArv2avm79I_PEQIywiU-tl_M6Bzp-FhHY',
    appId: '1:886121278075:web:24b6911126843e790a90de',
    messagingSenderId: '886121278075',
    projectId: 'app-thu-tien',
    authDomain: 'app-thu-tien.firebaseapp.com',
    storageBucket: 'app-thu-tien.appspot.com',
    measurementId: 'G-YCRDPH51GN',
  );
}